version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: jenkins
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.88.213:3306/recipenew
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: Password0
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  db:
    image: mysql:8
    hostname: db
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: recipenew
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Password0
      MYSQL_ROOT_PASSWORD: Password0
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - network

  app:
    image: irecipenew
    build:
      context: .
      dockerfile: jenkins/build/Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/recipenew
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
    stdin_open: true
    tty: true
    networks:
      - network


#  remote_host:
#    container_name: remote-host
#    image: remote-host
#    build:
#      context: centos7
#    networks:
#      - net
#  git:
#    container_name: git-server
#    image: 'gitlab/gitlab-ee:latest'
#    hostname: 'gitlab.example.com'
#    ports:
#      - '8090:80'
#    volumes:
#      - '$GITLAB_HOME/config:/etc/gitlab'
#      - '$GITLAB_HOME/logs:/var/log/gitlab'
#      - '$GITLAB_HOME/data:/var/opt/gitlab'
#    networks:
#      - net
volumes:
  db_data: {}
  db-list:
networks:
  net: