version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  db:
    container_name: db
    image: mysql:8
    hostname: db
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: recipenew
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Password0
      MYSQL_ROOT_PASSWORD: Password0
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
networks:
  net: